Created Docker images

diff --git a/video-server b/video-server
--- a/video-server
+++ b/video-server
@@ -11,10 +11,14 @@ done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
 # Executable jar file
-JAR=$DIR/target/video-server.jar
+JAR=$DIR/video-server.jar
+
+if [ ! -f "$JAR" ]; then
+  JAR=$DIR/target/video-server.jar
+fi
 
 # Build the jar
-if [ ! -f $JAR ]; then
+if [ ! -f "$JAR" ]; then
   pushd $DIR
 
   # Grab the latest android app
@@ -29,5 +33,9 @@ if [ ! -f $JAR ]; then
 fi
 
 # Execute the jar, passing the arguments
-java -jar $JAR $@
-
+if [ -f "$JAR" ]; then
+  exec java -jar "$JAR" $@
+else
+  echo "Could not find video-server.jar file"
+  exit 1
+fi
